language: rust
sudo: false

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

install:
  - rustup set profile minimal || exit 1;
  - rustup toolchain install nightly-2019-10-13 || exit 1;
  - rustup component add rustfmt --toolchain nightly-2019-10-13 || exit 1;
  - rustup component add clippy --toolchain nightly-2019-10-13 || exit 1;

before_script:
  - cargo fetch --verbose

script:
  - cargo +nightly-2019-10-13 fmt -- --check
  - cargo +nightly-2019-10-13 clippy --all --all-targets -- -D warnings
  - cargo build
  - cargo test
  - cargo bench

cache:
  timeout: 1000
  cargo: true
  directories:
    - "$HOME/.rustup"
before_cache:
  - rm -rf $HOME/.cargo/registry
  - rm -rf $TRAVIS_BUILD_DIR/target
