[package]
name = "secp256k1"
version = "0.7.0"
authors = [ "CodeChain Team <hi@codechain.io>",
            "Dawid Ciężarkiewicz <dpc@ucore.info>",
            "Andrew Poelstra <apoelstra@wpsoftware.net>" ]
license = "CC0-1.0"
homepage = "https://github.com/CodeChain-io/rust-secp256k1/"
repository = "https://github.com/CodeChain-io/rust-secp256k1/"
documentation = "https://www.wpsoftware.net/rustdoc/secp256k1/"
description = "Fork of Rust bindings for Pieter Wuille's `libsecp256k1` library. Implements ECDSA for the SECG elliptic curve group secp256k1 and related utilities."
keywords = [ "crypto", "ECDSA", "secp256k1", "libsecp256k1", "bitcoin" ]
readme = "README.md"
build = "build.rs"

[build-dependencies]
cc = "1.0"
cfg-if = "0.1"

[lib]
name = "secp256k1"
path = "src/lib.rs"

[features]
unstable = []
default = []
dev = ["clippy"]

[dependencies]
arrayvec = "0.4"
clippy = {version = "0.0", optional = true}
rand = "0.6"

[dev-dependencies]
hex-literal = "0.2"
rand_core = "0.4.2"
